<?php

/**
 * @file
 * Main file of Ctools Field module.
 */

/**
 * Implements hook_migrate_api().
 */
function ctools_field_migrate_api() {
  $api = array(
    'api' => 2,
    'field handlers' => array(
      'MigrateCtoolsFieldValueFieldHandler',
    ),
  );

  return $api;
}

/**
 * Implements hook_field_info().
 */
function ctools_field_field_info() {
  return array(
    'ctools_field' => array(
      'label' => t('Ctools field'),
      'description' => t('Stores ctools content.'),
      'settings' => array(),
      'default_widget' => 'ds_selector',
      'default_formatter' => 'ctools_field_formatter',
    ),
  );
}

/**
 * Implements hook_field_settings_form().
 */
function ctools_field_field_settings_form($field, $instance, $has_data) {
  $settings = $field['settings'];
  $form = array();

//  Example for later implementation
//  $form['decimal_separator'] = array(
//    '#type' => 'select',
//    '#title' => t('Decimal marker'),
//    '#options' => array('.' => t('Decimal point'), ',' => t('Comma')),
//    '#default_value' => $settings['decimal_separator'],
//    '#description' => t('The character users will input to mark the decimal point in forms.'),
//  );

  return $form;
}

/**
 * Implements hook_field_instance_settings_form().
 */
function ctools_field_field_instance_settings_form($field, $instance) {
  $settings = $instance['settings'];
  $form = array();

//  Example for later implementation
//  $form['prefix'] = array(
//    '#type' => 'textfield',
//    '#title' => t('Prefix'),
//    '#default_value' => $settings['prefix'],
//    '#size' => 60,
//    '#description' => t("Define a string that should be prefixed to the value, like '$ ' or '&euro; '. Leave blank for none. Separate singular and plural values with a pipe ('pound|pounds')."),
//  );

  return $form;
}

/**
 * Implements hook_field_validate().
 *
 */
function ctools_field_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
//  foreach ($items as $delta => $item) {
//    if ($item['value'] != '') {
//    }
//  }
}

/**
 * Implements hook_field_is_empty().
 */
function ctools_field_field_is_empty($item, $field) {
  // @todo: why is this ignored???
  if (empty($item['value']) && (string) $item['value'] !== '0') {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_field_formatter_info().
 */
function ctools_field_field_formatter_info() {
  return array(
    'ctools_field_formatter' => array(
      'label' => t('Default Formatter'),
      'field types' => array('ctools_field'),
      'settings' =>  array(
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function ctools_field_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function ctools_field_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = array();

  return implode('<br />', $summary);
}

/**
 * Implements hook_field_formatter_view().
 */
function ctools_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  foreach ($items as $delta => $item) {
    if (is_string($item['value'])) {
      $unserialized_value = unserialize($item['value']);
    } else {
      $unserialized_value = array();
    }

    $show_title = isset($unserialized_value['field_conf']['show_title']) ? $unserialized_value['field_conf']['show_title'] : false;
    $title_wrapper = isset($unserialized_value['field_conf']['title_wrapper']) ? $unserialized_value['field_conf']['title_wrapper'] : 'h3';

    $field = array(
      'entity_type' => $entity_type,
      'entity' => $entity,
      'formatter_settings' => array(
        'show_title' => $show_title,
        'title_wrapper' => $title_wrapper,
        'ctools' => $item['value'],
      ),
    );

    $rendered_content = ds_render_ctools_field($field);

    $element[$delta] = array('#markup' => $rendered_content);
  }


  return $element;
}

/**
 * Implements hook_field_widget_info().
 */
function ctools_field_field_widget_info() {
  return array(
    'ds_selector' => array(
      'label' => t('DS ctools selector'),
      'field types' => array('ctools_field'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function ctools_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $value = isset($items[$delta]['value']) ? $items[$delta]['value'] : FALSE;

  if (is_string($items[$delta]['value'])) {
    $unserialized_value = unserialize($items[$delta]['value']);
  } else {
    $unserialized_value = array();
  }

  $show_title = isset($unserialized_value['field_conf']['show_title']) ? $unserialized_value['field_conf']['show_title'] : false;
  $title_wrapper = isset($unserialized_value['field_conf']['title_wrapper']) ? $unserialized_value['field_conf']['title_wrapper'] : 'h3';

  /* Get ds form css & js */
  form_load_include($form_state, 'inc', 'ds', 'includes/ds.field_ui');
  $cloned_form = $element;
  $cloned_form['#view_mode'] = 'fake';
  $cloned_form['#submit'] = array();

  $fake_form_state = $form_state;
  ds_field_ui_fields_layouts($cloned_form, $fake_form_state);

  if (!array_key_exists('#attached', $form)) {
    $element['#attached'] = array();
  }
  $element['#attached'] = array_merge($element['#attached'], $cloned_form['#attached']);

  // Fake ds ctools/dynamic content field.
  $field = array(
    'entity_type' => $element['#entity_type'],
    'name' => $element['#field_name'],
    'properties' => array(
      'settings' => array(
        'ctools' => array(
          'type' => 'ctools',
        ),
      ),
    ),
  );

  if (!empty($value) && isset($unserialized_value['type'])) {
    $field['formatter_settings'] = array(
      'ctools' => $value,
    );
  }

  // Wrap our fields into a fieldset.
  $element['ctools_field'] = array(
    '#type' => 'fieldset',
    '#title' => $element['#title'],
    '#description' => $element['#description'],
  );

  // Load content select/edit field.
  $ds_field = ds_ds_field_settings_form($field);

  $element['ctools_field']['select'] = $ds_field['select'];

  // We need to change the parents so the ajax invoke can set the value
  $hidden_field = $ds_field['ctools'];
  $hidden_field['#parents'] = array(
    'fields',
    $field['name'],
    'settings_edit_form',
    'settings',
    'ctools',
  );
  $element['hidden'] = $hidden_field;

  $element['ctools_field']['show_title'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show title'),
    '#default_value' => $show_title,
  );

  $element['ctools_field']['title_wrapper'] = array(
    '#type' => 'textfield',
    '#title' => t('Title wrapper'),
    '#description' => t('Enter the HTML wrapper for the title output.'),
    '#default_value' => $title_wrapper,
    '#states' => array(
      'invisible' => array(
        'input[name$="[ctools_field][show_title]"]' => array('checked' => FALSE),
      ),
    ),
  );

  // Add a custom validation to set the correct field value.
  $element['#element_validate'][] = 'ctools_field_widget_validate';

  return array('value' => $element);
}

/**
 * Widget validation to set the correct field value.
 */
function ctools_field_widget_validate($element, &$form_state) {
  $field = field_widget_field($element, $form_state);
  $instance = field_widget_instance($element, $form_state);

  $show_title = $element['ctools_field']['show_title']['#value'];
  $title_wrapper = $element['ctools_field']['title_wrapper']['#value'];

  // Move the value from the hidden field to the field value.
  if (is_string($element['hidden']['#value'])) {
    $hidden_value = unserialize($element['hidden']['#value']);
  } else {
    $hidden_value = array();
  }

  $hidden_value['field_conf'] = array(
    'show_title' => $show_title,
    'title_wrapper' => $title_wrapper,
  );

  form_set_value($element, serialize($hidden_value), $form_state);
}

/**
 * Implements hook_field_widget_error().
 */
function ctools_field_field_widget_error($element, $error, $form, &$form_state) {
  form_error($element['value'], $error['message']);
}
